### ISSUE TITLE
Problems Accessing Invoxia

### ISSUE THREAD

**Issue by heap73** [timothyle97/Invoxia-HA#3]
Hi Timoty, first of all thanks for the nice job.
Im trying your integration and wondering if it still works as I am receiving a login error.

**Comment by scooper1** [comment]
is there any fix for the config flow login error  
thanks

**Comment by ThibautLM** [comment]
Hi! same comment as the people above. Itwould be really cool to be able to integrate invoxia into home assisant! thanks in advance

**Comment by merlinpimpim** [comment]
It doesn't work at all

**Comment by MagnusErler** [comment]
What is not working? It works fine for me

**Comment by merlinpimpim** [comment]
![image](https://github.com/timothyle97/Invoxia-HA/assets/113300765/8562d81a-9e46-4514-befe-04b83e0dd576)

Unexpected error when trying to enter my username/password

**Comment by MagnusErler** [comment]
What does the log say?

**Comment by merlinpimpim** [comment]
> What does the log say?

This:
> 2024-01-06 13:29:46.229 ERROR (MainThread) [custom_components.invoxia] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gps_tracker/client/datatypes.py", line 38, in form
    obj = cls(**data)
          ^^^^^^^^^^^
TypeError: TrackerConfig.__init__() missing 1 required positional argument: 'network_config'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/invoxia/config_flow.py", line 68, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/invoxia/config_flow.py", line 39, in validate_input
    await client.get_devices()
  File "/usr/local/lib/python3.11/site-packages/gps_tracker/client/asynchronous.py", line 153, in get_devices
    return [Device.get(item) for item in data]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gps_tracker/client/asynchronous.py", line 153, in 
    return [Device.get(item) for item in data]
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gps_tracker/client/datatypes.py", line 123, in get
    return form(Device._registry[device_data.pop("type")], device_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gps_tracker/client/datatypes.py", line 38, in form
    obj = cls(**data)
          ^^^^^^^^^^^
  File "", line 10, in __init__
    _setattr('tracker_config', __attr_converter_tracker_config(tracker_config))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gps_tracker/client/datatypes.py", line 386, in _tracker_config_converter
    return form(TrackerConfig, val)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gps_tracker/client/datatypes.py", line 49, in form
    raise UnknownAnswerScheme(data, err.args[0], cls) from err
gps_tracker.client.exceptions.UnknownAnswerScheme: 
It appears that one of your devices has fields which are not currently recognized.
Please open an issue at https://gitlab.com/ezlo.picori/gps_tracker with the following content:
{
    "mode": "235",
    "color": 0,
    "icon": 10,
    "notify_position": true,
    "notify_long_walk": false,
    "network": "lora",
    "network_region": "5",
    "firmware_path": "http://developer.invoxia.com/update/tracker/update.pup",
    "board_name": "LWT1v2",
    "usage": "vehicle"
}
TrackerConfig.__init__() missing 1 required positional argument: 'network_config' when instantiating .
Obfuscate any sensitive data by replacing letters by 'a' and digits by '0' if needed.

>

**Comment by MagnusErler** [comment]
Please do the following
```
It appears that one of your devices has fields which are not currently recognized.
Please open an issue at https://gitlab.com/ezlo.picori/gps_tracker with the following content:
{
"mode": "235",
"color": 0,
"icon": 10,
"notify_position": true,
"notify_long_walk": false,
"network": "lora",
"network_region": "5",
"firmware_path": "http://developer.invoxia.com/update/tracker/update.pup",
"board_name": "LWT1v2",
"usage": "vehicle"
}
```

**Comment by merlinpimpim** [comment]
Done

**Comment by merlinpimpim** [comment]
done
https://gitlab.com/ezlo.picori/gps_tracker/-/issues/8

**Comment by ezlo-picori** [comment]
Hi,

I updated the underlying `gps_tracker` to version 0.9.0 which hopefully will fix these issues after @merlinpimpim report.

You will need to update the `manifest.json` fill by setting `"requirements": ["gps-tracker==0.9.0"]` and by incrementing the line `"version": "1.0.0"` to a any value (e.g. `2.0.0`).

**Comment by merlinpimpim** [comment]
> Hi,
> 
> I updated the underlying `gps_tracker` to version 0.9.0 which hopefully will fix these issues after @merlinpimpim report.
> 
> You will need to update the `manifest.json` fill by setting `"requirements": ["gps-tracker==0.9.0"]` and by incrementing the line `"version": "1.0.0"` to a any value (e.g. `2.0.0`).

Supplementary question: I have 2 trackers in my Invoxia account but only 1 is shown in the integration. 
How can I get both?
If this isn't possible, is it possible to choose which of the 2 I'd prefer to retrieve in HA?
![image](https://github.com/timothyle97/Invoxia-HA/assets/113300765/b81b19f3-b9c8-4826-a62c-7e5888114083)

Thank you

**Comment by mpigou** [comment]
All your trackers are supposed to show up in home-assistant. I have two of them and they both show up correctly.

When I set-up the integration, it's true that at first I only see one entity but the second one appears by simply refreshing the page (F5).
If even after the initial setup the second tracker does not appear on home-assistant, maybe one of your device is not properly handled by the underlying API client?... What are their models?

**Comment by merlinpimpim** [comment]
> > Hi,
> > I updated the underlying `gps_tracker` to version 0.9.0 which hopefully will fix these issues after @merlinpimpim report.
> > You will need to update the `manifest.json` fill by setting `"requirements": ["gps-tracker==0.9.0"]` and by incrementing the line `"version": "1.0.0"` to a any value (e.g. `2.0.0`).
> 
> Super, it works! (Note: you need to restart HA after making these changes).
> 
> Supplementary question: I have 2 trackers in my Invoxia account but only 1 is shown in the integration. How can I get both? If this isn't possible, is it possible to choose which of the 2 I'd prefer to retrieve in HA? ![image](https://private-user-images.githubusercontent.com/113300765/302146507-b81b19f3-b9c8-4826-a62c-7e5888114083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTg2NzgsIm5iZiI6MTcwNzMxODM3OCwicGF0aCI6Ii8xMTMzMDA3NjUvMzAyMTQ2NTA3LWI4MWIxOWYzLWI5YzgtNDgyNi1hNjJjLTdlNTg4ODExNDA4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxNTA2MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03M2E4NDZlNTU0YTlmOTNlZjFkOGRiMWI1MjUyNTYyYTA4NTk3OTE5NjhkODFlZDIzOGI5ZDMzNmM5YTc2NTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._blEwuq2hyjQ_TvneGjU10JkxMlg-SpKVylvurvcsdw)
> 
> Thank you

@ezlo-picori An idea ?

**Comment by ezlo-picori** [comment]
Not really no, both devices are supposed to show up...

I have updated the integration on the initial pull request, maybe some of those changes could have an impact on the issue you are facing?... You can try by using the [updated integration](https://github.com/ezlo-picori/core/tree/gpstracker-integration/homeassistant/components/invoxia) to see if that fixes it. Otherwise I don't really know.

If you are confortable with python, you could also try using directly the [gps-tracker](https://gps-tracker.readthedocs.io/en/latest/start.html) package to see what devices are detected for your account. If one of your devices fails to load because it is not supported, you may open a dedicated issue (once again...).

**Comment by merlinpimpim** [comment]
It's ok now, my 2 devices are visible in the integration 😀
Thx

**Comment by timothyle97** [comment]
Sorry for the delay in updating this. I've made the suggested changes in manifest.json. Please let me know if there are any other issues.
