### ISSUE TITLE
Cannot update to 6aee533 from HACS

### ISSUE THREAD

**Issue by MonsieurPoutounours** [timothyle97/Invoxia-HA#7]
I am using version 79a5d52 and my system ask for upgrade to version 6aee533.

Yet, upgrade throws the following error : 

Échec de l'exécution de l'action update/install. The version 6aee533 for this integration can not be used with HACS.

**Comment by MagnusErler** [comment]
PR https://github.com/timothyle97/Invoxia-HA/pull/8

**Comment by MonsieurPoutounours** [comment]
Thank you both for this QoL upgrade !
